# ContestTrade 配置文件模板
# 请复制此文件为 config.yaml 并填入您的 API 密钥

# 可选：Tushare 数据接口密钥（用于获取更丰富的金融数据）
# 获取地址：https://tushare.pro/
tushare_key: "" 

# 可选：Bocha 搜索引擎密钥
# 获取地址：https://bocha.io/
bocha_key: "" 

# 可选：SerpAPI 搜索引擎密钥
# 获取地址：https://serpapi.com/
serp_key: "" 

# 可选：FMP 金融数据密钥
fmp_key: "" 

# 可选：Finnhub 金融数据密钥
finnhub_key: "" 

# 必需：LLM API 配置（用于通用任务）
# 推荐使用 DeepSeek API
llm:
  base_url: "https://api.deepseek.com"
  api_key: "sk-46fd5137f830427a916c9c439d87df0b"
  model_name: "deepseek-chat"

# 可选：用于复杂推理的 LLM API
llm_thinking:
  base_url: "https://api.deepseek.com"
  api_key: "sk-46fd5137f830427a916c9c439d87df0b"
  model_name: "deepseek-reasoner"

# 可选：用于视觉分析的 VLM API
vlm:
  base_url: "https://api.deepseek.com"
  api_key: "sk-46fd5137f830427a916c9c439d87df0b"
  model_name: "deepseek-chat"

# 数据智能体配置（使用 AKShare 数据源）
data_agents_config:
  - agent_name: "sina_summary_agent"
    data_source_list: 
      - "data_source.sina_news_crawl.SinaNewsCrawl"
  - agent_name: "thx_summary_agent"
    data_source_list: 
      - "data_source.thx_news_crawl.ThxNewsCrawl"
  - agent_name: "price_market_agent"
    data_source_list: 
      - "data_source.price_market_akshare.PriceMarketAkshare"
  - agent_name: "hot_money_agent"
    data_source_list: 
      - "data_source.hot_money_akshare.HotMoneyAkshare"
  - agent_name: "community_sentiment_agent"
    data_source_list:
      - "data_source.xueqiu_community_crawl.XueqiuCommunityCrawl"
      - "data_source.eastmoney_community_crawl.EastmoneyCommunityCrawl"
    bias_goal: "专注于捕获市场情绪变化、KOL观点分析和投资者行为模式，识别潜在的催化剂事件和情绪拐点"
    final_target_tokens: 5000

# 研究智能体配置
research_agent_config:
  belief_list_path: "config/belief_list.json"
  max_react_step: 10
  output_language: "中文"
  tools:
    - "tools.stock_symbol_search_akshare.stock_symbol_search"
    - "tools.stock_selector_akshare.stock_selector"
    - "tools.corp_info_akshare.company_financial_info"
    - "tools.price_info_akshare.price_info"
    - "tools.search_web.search_web"
    - "tools.stock_summary_akshare.stock_summary"
    - "tools.final_report.final_report"

# 系统语言设置
system_language: "中文"

# 研究员竞赛配置
researcher_contest_config:
  contest_mode: False
  judger_config: llm
  num_judgers: 3
  window_m: 3
  window_n: 3
